export interface PlanProduccion {
    planProduccionId:          number;
    labor_id:                  number;
    periodo_id:                number;
    ancho_veta_metros:         number;
    ancho_minado_sem_metros:   number;
    ancho_minado_mes_metros:   number;
    ag_gr:                     number;
    porcentaje_cu:             number;
    porcentaje_pb:             number;
    porcentaje_zn:             number | null;
    vpt_actual:                number;
    vpt_final:                 number;
    cut_off_1:                 number;
    cut_off_2:                 number;
    mina_id:                   number;
    zona_id:                   number;
    area_id:                   number;
    fase_id:                   number;
    tipo_labor_id:             number;
    estructura_mineral_id:     number;
    nivel_id:                  number;
    ala_id:                    number | null;
    labor_nombre:              string;
    mina_nombre:               string;
    zona_nombre:               string;
    area_nombre:               string;
    fase_nombre:               string;
    tipo_labor_nombre:         string;
    estructura_mineral_nombre: string;
    nivel_nombre:              string;
    ala_nombre:                null | string;
    created_at:                Date;
    updated_at:                Date;
}